version: '3'

services:
  backend:
    build:
      context: ./chat-backend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./chat-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
