# Stage 1: Build the React app
FROM node:alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install -g npm@10.5.0  # Update npm
RUN npm install --force  # Force dependency resolution

COPY . .

RUN npm run build

# Stage 2: Serve the React app using Nginx
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
